const STATUS_CREATED = 201;
const STATUS_OK = 200;
const INTERNAL_SERVER_ERROR = 500;
const MONGO_URL_DEV = 'mongodb://127.0.0.1:27017/bitfilmsd';

module.exports = {
  STATUS_CREATED,
  STATUS_OK,
  INTERNAL_SERVER_ERROR,
  MONGO_URL_DEV,
};
